### ISSUE TITLE
Ncaa BB scrape doesnt return current players

### ISSUE THREAD

**Issue by goose2288** [mattheworres/hootdraft-scraper#9]
So I downloaded this and ran the scrape for NCAABB and it does return a csv file with the players but they are from last year.  New players for this year are not in the file.  Any ideas?  Thanks so much

**Comment by mattheworres** [comment]
Just checked, and it looks like CBS has finally updated a lot of those pages after years of them never changing (and why I scraped them!). NCAA Mens Basketball seems to be a holder on, because I checked NFL, NBA and NHL and none of those leagues even return pages, just a 404 Fumble (not found) page is returned. I'll have to investigate more tonight and see if there's a quick way to rewrite the scraper, but I may need to revamp how it's done as each sport _may_ need its own specific scrape now.

**Comment by goose2288** [comment]
Gotcha!  Thanks for the reply!

**Comment by mattheworres** [comment]
Looks like the others are broken as well - at a very high level (it's been a while since I've done anything with this code, I think I updated it to ES6 last time but didn't rewrite it just updated syntax) I will need to:
- Find a new data source(s) to scrape. Hopefully one source will support all, but I'll likely need to...
- Separate out scraper from the scrape process. Allow for sports to be associated with different scrapers

Code wise this sounds like a fun problem to solve (and I hope to get something in place for football this summer) but splitting away from 1 source to possibly multiple makes the code more fragile (the entire reason I dragged my feet writing a scraper - its inherently fragile) and I've just not had the free time/gumption to take care of this repo (or any of my other hobby projects).

I encourage folks to fork the repo and try your own hand if you can't wait on me (no hard feelings from me) - but I'll try to get something going here at some point.
